# Generated by Django 6.0.6 on 2026-06-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('api_secret', models.CharField(max_length=128)),
                ('access_token', models.CharField(blank=True, default='', max_length=128)),
                ('user_id', models.CharField(blank=True, default='', max_length=32)),
                ('user_name', models.CharField(blank=True, default='', max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
