# Generated by Django 6.0.6 on 2026-06-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiteuser',
            name='manual_token',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kiteuser',
            name='api_secret',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
