# Generated by Django 6.0.6 on 2026-06-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_backfill_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('self_only', 'Self only'), ('admin_only', 'Admin only'), ('trader_all', 'Trader all')], default='self_only', max_length=16),
        ),
    ]
