# Generated by Django 6.0.6 on 2026-06-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiteuser',
            name='refresh_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
