# Generated by Django 6.0.6 on 2026-07-01 18:52

import app.models
from django.db import migrations, models
import uuid


def populate_zk_user_ids(apps, schema_editor):
    KiteUser = apps.get_model('app', 'KiteUser')
    existing = set(
        KiteUser.objects.exclude(zk_user_id='').values_list('zk_user_id', flat=True)
    )
    for item in KiteUser.objects.all().iterator():
        if item.zk_user_id:
            continue
        candidate = ''
        while not candidate or candidate in existing:
            candidate = 'ZK{0}'.format(uuid.uuid4().hex[:12].upper())
        item.zk_user_id = candidate
        item.save(update_fields=['zk_user_id'])
        existing.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_kiteuser_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiteuser',
            name='automate',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kiteuser',
            name='zerodha_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='kiteuser',
            name='zerodha_totp_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='kiteuser',
            name='zk_user_id',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.RunPython(populate_zk_user_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='kiteuser',
            name='zk_user_id',
            field=models.CharField(default=app.models.generate_kite_user_identifier, max_length=24, unique=True),
        ),
    ]
