# Generated by Django 6.0.6 on 2026-07-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_kiteuser_automate_kiteuser_zerodha_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiteuser',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
