# Generated by Django 6.0.6 on 2026-07-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_kiteuser_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiteuser',
            name='automate',
        ),
        migrations.RemoveField(
            model_name='kiteuser',
            name='manual_token',
        ),
        migrations.RemoveField(
            model_name='kiteuser',
            name='zerodha_password',
        ),
        migrations.RemoveField(
            model_name='kiteuser',
            name='zerodha_totp_key',
        ),
    ]
